[package]
name = "near-rust-allocator-proxy"
version = "0.2.1"
authors = ["Piotr Mikulski <piotr@near.org>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
libc = "0.2.65"
backtrace = "0.3"
arr_macro = "0.1.3"
log = "0.4"
jemalloc-sys = "0.3.2"
jemallocator = { version = "0.3"  }
nix = "0.15.0"


